### ISSUE TITLE
missing or corrupt files when training esc-50 model

### ISSUE THREAD

**Issue by Djoels** [YuanGongND/ast#41]
Upon trying to run the ESC-50 recipe, I come across the following error:
```
formats: can't open input file `/project/ast/data/ESC-50-master/audio/1-31836-A-4.wav': Input/output error
Epoch: [1][100/134]     Per Sample Total Time 0.07304   Per Sample Data Time 0.00930    Per Sample DNN Time 0.06374     Train Loss 2.7119
Traceback (most recent call last):
  File "../../src/run.py", line 99, in <module>
    train(audio_model, train_loader, val_loader, args)
  File "/project/ai-audio-classification-models/06-audio-spectrogram-transformer/src/traintest.py", line 100, in train
    for i, (audio_input, labels) in enumerate(train_loader):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 28.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/project/ai-audio-classification-models/06-audio-spectrogram-transformer/src/dataloader.py", line 180, in __getitem__
  File "/project/ai-audio-classification-models/06-audio-spectrogram-transformer/src/dataloader.py", line 101, in _wav2fbank
  File "/opt/conda/lib/python3.7/site-packages/torchaudio/backend/sox_io_backend.py", line 153, in load
    filepath, frame_offset, num_frames, normalize, channels_first, format)
RuntimeError: Error loading audio file: failed to open file /project/ast/data/ESC-50-master/audio/1-31836-A-4.wav
```
It's quite unclear to me how this could happen, maybe the sox command fails and the file is therefor not created?
This happens in almost every fold.

**Comment by YuanGongND** [comment]
It seems to be an error of ``prep_esc50.py``. Can you check the files in ``./data/ESC-50-master/audio`` (audio files before sox processing) is complete? If not, you can remove the entire ``./data/ESC-50-master`` and run ``prep_esc50.py`` again.

**Comment by Djoels** [comment]
ah, it seems I had misunderstood the script and messed up the paths. 
also it seems sox wasn't properly installed on my system. 
so I'm guessing rectifying these issues will actually take care of it
