### ISSUE TITLE
How to change the interpolation method?

### ISSUE THREAD

**Issue by ooobsidian** [YuanGongND/ast#44]
Hi Yuan,
    In the AST, for the part of the ablation experiment comparing different interpolation methods, one of the items is called "Reinitialize", how is this reflected in the code?
Best Regards.

**Comment by YuanGongND** [comment]
The code is in https://github.com/YuanGongND/ast/blob/7252ecec6baf4cc81c7fecd0b6bfabc8e484b685/src/models/ast_models.py#L109-L113

-Yuan

**Comment by YuanGongND** [comment]
Copy these lines of code to place where you want to reinitialize the positional embedding.

**Comment by ooobsidian** [comment]
Great. Thank you so much!

**Comment by ooobsidian** [comment]
Hi Yuan,
I have used the Reinitialize method in my code and an error occurs when I do the model initialization.
```python
Traceback (most recent call last):
  File "train.py", line 399, in <module>
    main()
  File "train.py", line 128, in main
    model = ASTModel(input_tdim=args.length, input_fdim=c.FILTER_BANK, label_dim=n_classes, embed_dim=c.EMBEDDING_DIM, tstride=args.tstride, fstride=args.fstride, audioset_pretrain=args.audioset_pretrain, imagenet_pretrain=args.imagenet_pretrain)
  File "/data/source/deepAST_exp/model/ASTConcat.py", line 119, in __init__
    new_pos_embed = new_pos_embed[:, :, int(self.oringal_hw / 2) - int(f_dim / 2): int(self.oringal_hw / 2) - int(f_dim / 2) + f_dim, :]
IndexError: too many indices for tensor of dimension 3
```

My code for this part is as follows:
```python
if imagenet_pretrain == True:
                # get the positional embedding from deit model, skip the first two tokens (cls token and distillation token), reshape it to original 2D shape (24*24).
                new_pos_embed = self.v.pos_embed[:, 2:, :].detach().reshape(1, self.original_num_patches, self.original_embedding_dim).transpose(1, 2).reshape(1, self.original_embedding_dim, self.oringal_hw, self.oringal_hw)
                # cut (from middle) or interpolate the second dimension of the positional embedding
                if t_dim <= self.oringal_hw:
                    new_pos_embed = new_pos_embed[:, :, :, int(self.oringal_hw / 2) - int(t_dim / 2): int(self.oringal_hw / 2) - int(t_dim / 2) + t_dim]
                else:
                    # print('Use bilinear interpolate.')
                    # new_pos_embed = torch.nn.functional.interpolate(new_pos_embed, size=(self.oringal_hw, t_dim), mode='bilinear')
                    # print("=========================")
                    # print('Use nearest interpolate.')
                    # print("=========================")
                    # new_pos_embed = torch.nn.functional.interpolate(new_pos_embed, size=(self.oringal_hw, t_dim))
                    print("============================")
                    print('Use reinitialize interpolate.')
                    print("============================")
                    new_pos_embed = nn.Parameter(torch.zeros(1,self.original_embedding_dim, self.v.patch_embed.num_patches + 2 ))
                    self.v.pos_embed = new_pos_embed
                    trunc_normal_(self.v.pos_embed, std=.02)
                # cut (from middle) or interpolate the first dimension of the positional embedding
                if f_dim <= self.oringal_hw:
                    new_pos_embed = new_pos_embed[:, :, int(self.oringal_hw / 2) - int(f_dim / 2): int(self.oringal_hw / 2) - int(f_dim / 2) + f_dim, :]
                else:
                    new_pos_embed = torch.nn.functional.interpolate(new_pos_embed, size=(f_dim, t_dim), mode='bilinear')
                # flatten the positional embedding
                new_pos_embed = new_pos_embed.reshape(1, self.original_embedding_dim, num_patches).transpose(1,2)
                # concatenate the above positional embedding with the cls token and distillation token of the deit model.
                self.v.pos_embed = nn.Parameter(torch.cat([self.v.pos_embed[:, :2, :].detach(), new_pos_embed], dim=1))
            else:
                # if not use imagenet pretrained model, just randomly initialize a learnable positional embedding
                # TODO can use sinusoidal positional embedding instead
                new_pos_embed = nn.Parameter(torch.zeros(1, self.v.patch_embed.num_patches + 2, self.original_embedding_dim))
                self.v.pos_embed = new_pos_embed
                trunc_normal_(self.v.pos_embed, std=.02)
```

**Comment by YuanGongND** [comment]
Basically, you don't need to cut/interpolate the positional embedding if you want to reinitialize it. So 
```
if f_dim <= self.oringal_hw:
                    new_pos_embed = new_pos_embed[:, :, int(self.oringal_hw / 2) - int(f_dim / 2): int(self.oringal_hw / 2) - int(f_dim / 2) + f_dim, :]
                else:
                    new_pos_embed = torch.nn.functional.interpolate(new_pos_embed, size=(f_dim, t_dim), mode='bilinear')
                # flatten the positional embedding
                new_pos_embed = new_pos_embed.reshape(1, self.original_embedding_dim, num_patches).transpose(1,2)
                # concatenate the above positional embedding with the cls token and distillation token of the deit model.
                self.v.pos_embed = nn.Parameter(torch.cat([self.v.pos_embed[:, :2, :].detach(), new_pos_embed], dim=1))

```

is not necessary and is the reason the compiler complains. 

I don't have time to read the code, but it seems another error on the shape of `new_pos_embed` ,  it should be 

```
                new_pos_embed = nn.Parameter(torch.zeros(1, self.v.patch_embed.num_patches + 2, self.original_embedding_dim))
                self.v.pos_embed = new_pos_embed
                trunc_normal_(self.v.pos_embed, std=.02)
```

**Comment by ooobsidian** [comment]
Sorry for the trouble due to my lack of skill with the code, but thank you very much!
